### PR TITLE
chore: Update CI

### PR DESCRIPTION
**Pull request by erikmd**

### CODE REVIEW

**Comment by erikmd** [comment]
Thanks @proux01 for your commit!

BTW I commented-out this test line:
```
- mathcomp/mathcomp:1.15.0-coq-8.13
```

Indeed albeit  mathcomp 1.15.0 & coq 8.13 are compatible:
* coq-mathcomp-analysis 0.5.2- supports coq 8.13 but **NOT** mathcomp 1.15.0
* coq-mathcomp-analysis 0.5.2+ supports mathcomp 1.15.0 but **NOT** coq 8.13

But I suspect that one of these constraints could be lifted…

as a core committer in mathcomp analysis, do you think you could have a look?

**Comment by proux01** [comment]
Can't we just drop Coq 8.13?

**Comment by erikmd** [comment]
> Can't we just drop Coq 8.13?

Yes, looks OK to me: maintaining compatibility with Coq {8.14, 8.15, 8.16} looks sensible already 😅

Will amend my commit

**Comment by proux01** [comment]
Coq 8.16 is working but why
```
<><> Repository configuration for switch 4.13.1+flambda <><><><><><><><><><><><>
   1 coq-core-dev  https://coq.inria.fr/opam/core-dev
   2 coq-extra-dev https://coq.inria.fr/opam/extra-dev
   3 coq-released  https://coq.inria.fr/opam/released
   4 default       https://opam.ocaml.org/
```
this leads to the installation of dev versions of dependencies which is likely not what we want (except on master)?

**Pull request merged**
