### PR TITLE
Compile with Coq master

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by proux01** [comment]
@erikmd CI green except for master for which we get
```
 Error response from daemon: manifest for mathcomp/mathcomp:latest-coq-dev not found: manifest unknown: manifest unknown
```
Maybe we could merge (works locally), WDYT?

**Comment by erikmd** [comment]
@proux01 I don't think this is a spurious failure.

* On the one hand, mathcomp/mathcomp:latest-coq-dev had been removed on-purpose because the latest stable mathcomp is **NOT** compatible with coq.dev
* On the other hand, mathcomp/mathcomp-dev:coq-dev is stalled (you know, because of the expiration of MathComp CI minutes)

Actually, I guess we could propose on MathComp's Zulip to **remove all the `mathcomp*-coq-dev` images** because it's *better to fail in an expected way than succeed in an unexpected way*.

But regarding this CI PR #15, I guess the best trick to workaround all this amounts to replacing `mathcomp/mathcomp:latest-coq-dev` with `coqorg/coq:dev` (a bit longer of course, but up-to-date)

**Comment by proux01** [comment]
> Actually, I guess we could propose on MathComp's Zulip to **remove all the `mathcomp*-coq-dev` images temporarily** because _it's better to fail in an expected way than to succeed in an unexpected way_.

Well, October is in 10 days, I'd rather not do anything now and see how things fare in October since MC should now consume much less.

**Comment by proux01** [comment]
CI green, let's merge

**Pull request merged**
